In [2]:
import numpy as np
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [8]:
data = np.random.randn(2,3)
data

array([[-0.60176206, -0.59052325, -0.26950474],
       [ 0.64594784, -0.94874802, -0.44985541]])

In [9]:
data*10

array([[-6.01762057, -5.90523249, -2.69504738],
       [ 6.45947837, -9.48748016, -4.4985541 ]])

In [10]:
data+data

array([[-1.20352411, -1.1810465 , -0.53900948],
       [ 1.29189567, -1.89749603, -0.89971082]])

In [13]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

In [18]:
data1 = [6,7,5,8,0,1]
data1

[6, 7, 5, 8, 0, 1]

In [17]:
arr1 = np.array(data1)
arr1

array([6, 7, 5, 8, 0, 1])

In [25]:
data2 = [[6,7,5,8,0,1],[1,2,3,4,5,6]]
data2

[[6, 7, 5, 8, 0, 1], [1, 2, 3, 4, 5, 6]]

In [26]:
arr2 = np.array(data2)
arr2

array([[6, 7, 5, 8, 0, 1],
       [1, 2, 3, 4, 5, 6]])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [32]:
np.empty((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

arange 是range的数组版

In [36]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])