In [2]:
import numpy as np
import pandas as pd
import matplotlib as plt
my_arr = np.arange(1000000)
my_list = list(range(1000000))

In [8]:
data = np.random.randn(2,3)
data

array([[-0.60176206, -0.59052325, -0.26950474],
       [ 0.64594784, -0.94874802, -0.44985541]])

In [9]:
data*10

array([[-6.01762057, -5.90523249, -2.69504738],
       [ 6.45947837, -9.48748016, -4.4985541 ]])

In [10]:
data+data

array([[-1.20352411, -1.1810465 , -0.53900948],
       [ 1.29189567, -1.89749603, -0.89971082]])

In [13]:
data.shape

(2, 3)

In [15]:
data.dtype

dtype('float64')

In [18]:
data1 = [6,7,5,8,0,1]
data1

[6, 7, 5, 8, 0, 1]

In [17]:
arr1 = np.array(data1)
arr1

array([6, 7, 5, 8, 0, 1])

In [25]:
data2 = [[6,7,5,8,0,1],[1,2,3,4,5,6]]
data2

[[6, 7, 5, 8, 0, 1], [1, 2, 3, 4, 5, 6]]

In [26]:
arr2 = np.array(data2)
arr2

array([[6, 7, 5, 8, 0, 1],
       [1, 2, 3, 4, 5, 6]])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [32]:
np.empty((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

arange 是range的数组版

In [40]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

列表*数字 可以生成array数组

In [41]:
np.array([3] * 5,dtype='int32')

array([3, 3, 3, 3, 3], dtype=int32)

# pandas部分
https://pyzh.readthedocs.io/en/latest/python-pandas.html

In [5]:
s = pd.Series([1,3,5,np.nan,6,8])
s


0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [8]:
dates = pd.date_range('20191003',periods=6)
dates

DatetimeIndex(['2019-10-03', '2019-10-04', '2019-10-05', '2019-10-06',
               '2019-10-07', '2019-10-08'],
              dtype='datetime64[ns]', freq='D')

In [21]:
df = pd.DataFrame(np.random.randn(6,4),index = dates,columns = ['小爱同学','小米同学','小孙同学','小杨同学'])
df

小爱同学      小米同学      小孙同学      小杨同学
2019-10-03 -1.572427  0.733531 -0.539147  0.575574
2019-10-04  0.119424  0.773296 -0.342647  0.951565
2019-10-05 -1.019628 -1.661953  0.972271  0.159800
2019-10-06 -0.884763 -0.177808  0.199810  0.735441
2019-10-07 -0.800627  1.196700  0.913691  0.533029
2019-10-08 -0.946674 -0.399264  0.643931 -0.680529

传递字典对象来创建DataFrame

In [39]:
df2 = pd.DataFrame( {
                        'A' : 1.,
                        #单个值自适应表格
                       'B' : pd.Timestamp('20130102'),
                        #pd.Timestamp时间格式转换
                       'C' : pd.Series(1,index=list(range(5)),dtype='float32'),
                        #Series可以拼成DataFrame
                       'D' : np.array([3] * 5,dtype='int32'),
                        #np.array 也可以生成DataFrame
                       'E' : pd.Categorical(["test","train","test","train",'wd']),
                        #Categorical 是分类变量
                       'F' : 'foo' }
                     )

df2


A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo
4  1.0 2013-01-02  1.0  3     wd  foo

查看各列的dtypes

In [45]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

In [48]:
df2.A

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: A, dtype: float64

In [50]:
df.head()

小爱同学      小米同学      小孙同学      小杨同学
2019-10-03 -1.572427  0.733531 -0.539147  0.575574
2019-10-04  0.119424  0.773296 -0.342647  0.951565
2019-10-05 -1.019628 -1.661953  0.972271  0.159800
2019-10-06 -0.884763 -0.177808  0.199810  0.735441
2019-10-07 -0.800627  1.196700  0.913691  0.533029

In [65]:
print(df.index ,'\n')
print(df.columns,'\n')
print(df.values,'\n')
print(df.describe(),'\n')

DatetimeIndex(['2019-10-03', '2019-10-04', '2019-10-05', '2019-10-06',
               '2019-10-07', '2019-10-08'],
              dtype='datetime64[ns]', freq='D') 

Index(['小爱同学', '小米同学', '小孙同学', '小杨同学'], dtype='object') 

[[-1.57242734  0.73353094 -0.53914682  0.57557421]
 [ 0.11942439  0.77329576 -0.34264689  0.95156461]
 [-1.0196285  -1.66195284  0.97227127  0.15979977]
 [-0.88476295 -0.17780817  0.19980957  0.73544104]
 [-0.80062707  1.19670032  0.91369057  0.5330293 ]
 [-0.94667433 -0.39926362  0.64393109 -0.68052872]] 

           小爱同学      小米同学      小孙同学      小杨同学
count  6.000000  6.000000  6.000000  6.000000
mean  -0.850783  0.077417  0.307985  0.379147
std    0.548352  1.047406  0.643999  0.581016
min   -1.572427 -1.661953 -0.539147 -0.680529
25%   -1.001390 -0.343900 -0.207033  0.253107
50%   -0.915719  0.277861  0.421870  0.554302
75%   -0.821661  0.763355  0.846251  0.695474
max    0.119424  1.196700  0.972271  0.951565 



按 axis 排序 axis =0是横轴 =1是纵轴

In [69]:
df.sort_index(axis=0,ascending=False)

小爱同学      小米同学      小孙同学      小杨同学
2019-10-08 -0.946674 -0.399264  0.643931 -0.680529
2019-10-07 -0.800627  1.196700  0.913691  0.533029
2019-10-06 -0.884763 -0.177808  0.199810  0.735441
2019-10-05 -1.019628 -1.661953  0.972271  0.159800
2019-10-04  0.119424  0.773296 -0.342647  0.951565
2019-10-03 -1.572427  0.733531 -0.539147  0.575574

In [72]:
df.sort_values(by='小爱同学')

小爱同学      小米同学      小孙同学      小杨同学
2019-10-03 -1.572427  0.733531 -0.539147  0.575574
2019-10-05 -1.019628 -1.661953  0.972271  0.159800
2019-10-08 -0.946674 -0.399264  0.643931 -0.680529
2019-10-06 -0.884763 -0.177808  0.199810  0.735441
2019-10-07 -0.800627  1.196700  0.913691  0.533029
2019-10-04  0.119424  0.773296 -0.342647  0.951565

df['A']相当于df.A

In [74]:
df2['A']

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
Name: A, dtype: float64

切片查询

In [75]:
df[0:3]

小爱同学      小米同学      小孙同学      小杨同学
2019-10-03 -1.572427  0.733531 -0.539147  0.575574
2019-10-04  0.119424  0.773296 -0.342647  0.951565
2019-10-05 -1.019628 -1.661953  0.972271  0.159800

标签式选择

In [79]:
print(df.loc['2019-10-04'])
df.loc[dates[0]]

小爱同学    0.119424
小米同学    0.773296
小孙同学   -0.342647
小杨同学    0.951565
Name: 2019-10-04 00:00:00, dtype: float64


小爱同学   -1.572427
小米同学    0.733531
小孙同学   -0.539147
小杨同学    0.575574
Name: 2019-10-03 00:00:00, dtype: float64

通过标签获得多轴数据

In [91]:
print(df.loc[dates[0]:dates[3],['小爱同学','小孙同学']])
df.loc['2019-10-03':'2019-10-05',['小爱同学','小孙同学']]

                小爱同学      小孙同学
2019-10-03 -1.572427 -0.539147
2019-10-04  0.119424 -0.342647
2019-10-05 -1.019628  0.972271
2019-10-06 -0.884763  0.199810


小爱同学      小孙同学
2019-10-03 -1.572427 -0.539147
2019-10-04  0.119424 -0.342647
2019-10-05 -1.019628  0.972271

In [88]:
df.loc['2019-10-03',['小爱同学','小孙同学']]

小爱同学   -1.572427
小孙同学   -0.539147
Name: 2019-10-03 00:00:00, dtype: float64

In [92]:
df.loc[dates[0],'小爱同学']

-1.5724273382937399

位置式选择

In [94]:
df.iloc[3,0]

-0.884762947934712

In [95]:
df.iloc[3:,0:3]

小爱同学      小米同学      小孙同学
2019-10-06 -0.884763 -0.177808  0.199810
2019-10-07 -0.800627  1.196700  0.913691
2019-10-08 -0.946674 -0.399264  0.643931

指定列表位置

In [96]:
df.iloc[[1,2],[1,2]]

小米同学      小孙同学
2019-10-04  0.773296 -0.342647
2019-10-05 -1.661953  0.972271

对行切片

In [97]:
df.iloc[:,:]

小爱同学      小米同学      小孙同学      小杨同学
2019-10-03 -1.572427  0.733531 -0.539147  0.575574
2019-10-04  0.119424  0.773296 -0.342647  0.951565
2019-10-05 -1.019628 -1.661953  0.972271  0.159800
2019-10-06 -0.884763 -0.177808  0.199810  0.735441
2019-10-07 -0.800627  1.196700  0.913691  0.533029
2019-10-08 -0.946674 -0.399264  0.643931 -0.680529

In [99]:
df.iloc[1,1]

0.77329576442769421

boolean索引

In [101]:
df[df.小爱同学>0]

小爱同学      小米同学      小孙同学      小杨同学
2019-10-04  0.119424  0.773296 -0.342647  0.951565

In [102]:
df[df>0]

小爱同学      小米同学      小孙同学      小杨同学
2019-10-03       NaN  0.733531       NaN  0.575574
2019-10-04  0.119424  0.773296       NaN  0.951565
2019-10-05       NaN       NaN  0.972271  0.159800
2019-10-06       NaN       NaN  0.199810  0.735441
2019-10-07       NaN  1.196700  0.913691  0.533029
2019-10-08       NaN       NaN  0.643931       NaN

In [109]:
df2 = df.copy()
df2['小牛牛']=[1,2,3,4,5,6]
print(df2[df2['小牛牛'].isin([1,2])])
print(df2)

                小爱同学      小米同学      小孙同学      小杨同学  小牛牛
2019-10-03 -1.572427  0.733531 -0.539147  0.575574    1
2019-10-04  0.119424  0.773296 -0.342647  0.951565    2
                小爱同学      小米同学      小孙同学      小杨同学  小牛牛
2019-10-03 -1.572427  0.733531 -0.539147  0.575574    1
2019-10-04  0.119424  0.773296 -0.342647  0.951565    2
2019-10-05 -1.019628 -1.661953  0.972271  0.159800    3
2019-10-06 -0.884763 -0.177808  0.199810  0.735441    4
2019-10-07 -0.800627  1.196700  0.913691  0.533029    5
2019-10-08 -0.946674 -0.399264  0.643931 -0.680529    6


新增数据

In [117]:
s1 = pd.Series([x for x in range(1,7)],index = pd.date_range('20191003',periods=6))
s1
df['小牛奶'] = s1
df.loc[:,:]

小爱同学      小米同学      小孙同学      小杨同学  小牛奶
2019-10-03 -1.572427  0.733531 -0.539147  0.575574    1
2019-10-04  0.119424  0.773296 -0.342647  0.951565    2
2019-10-05 -1.019628 -1.661953  0.972271  0.159800    3
2019-10-06 -0.884763 -0.177808  0.199810  0.735441    4
2019-10-07 -0.800627  1.196700  0.913691  0.533029    5
2019-10-08 -0.946674 -0.399264  0.643931 -0.680529    6

In [120]:
df.loc[dates[0],'小爱同学']=10
df

小爱同学      小米同学      小孙同学      小杨同学  小牛奶
2019-10-03  10.000000  0.733531 -0.539147  0.575574    1
2019-10-04   0.119424  0.773296 -0.342647  0.951565    2
2019-10-05  -1.019628 -1.661953  0.972271  0.159800    3
2019-10-06  -0.884763 -0.177808  0.199810  0.735441    4
2019-10-07  -0.800627  1.196700  0.913691  0.533029    5
2019-10-08  -0.946674 -0.399264  0.643931 -0.680529    6

In [123]:
df.iloc[0:3,0:1]=np.random.rand(3,1)
df

小爱同学      小米同学      小孙同学      小杨同学  小牛奶
2019-10-03  0.135335  0.733531 -0.539147  0.575574    1
2019-10-04  0.575279  0.773296 -0.342647  0.951565    2
2019-10-05  0.629984 -1.661953  0.972271  0.159800    3
2019-10-06 -0.884763 -0.177808  0.199810  0.735441    4
2019-10-07 -0.800627  1.196700  0.913691  0.533029    5
2019-10-08 -0.946674 -0.399264  0.643931 -0.680529    6

In [124]:
len(df)

6

In [129]:
df.loc[:,"小爱同学"]=np.array([x*x for x in range(1,len(df)+1)])
df

小爱同学      小米同学      小孙同学      小杨同学  小牛奶
2019-10-03     1  0.733531 -0.539147  0.575574    1
2019-10-04     4  0.773296 -0.342647  0.951565    2
2019-10-05     9 -1.661953  0.972271  0.159800    3
2019-10-06    16 -0.177808  0.199810  0.735441    4
2019-10-07    25  1.196700  0.913691  0.533029    5
2019-10-08    36 -0.399264  0.643931 -0.680529    6

In [130]:
df2 = df.copy()
df2[df2<0]=-df2
df2

小爱同学      小米同学      小孙同学      小杨同学  小牛奶
2019-10-03     1  0.733531  0.539147  0.575574    1
2019-10-04     4  0.773296  0.342647  0.951565    2
2019-10-05     9  1.661953  0.972271  0.159800    3
2019-10-06    16  0.177808  0.199810  0.735441    4
2019-10-07    25  1.196700  0.913691  0.533029    5
2019-10-08    36  0.399264  0.643931  0.680529    6

### 缺失数据的处理

In [134]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['小猪'])
df1.loc[dates[0]:dates[1],'小猪']=1
df1


小爱同学      小米同学      小孙同学      小杨同学  小牛奶   小猪
2019-10-03     1  0.733531 -0.539147  0.575574    1  1.0
2019-10-04     4  0.773296 -0.342647  0.951565    2  1.0
2019-10-05     9 -1.661953  0.972271  0.159800    3  NaN
2019-10-06    16 -0.177808  0.199810  0.735441    4  NaN

丢掉含有缺失项的行

In [137]:
df1.dropna(how ='any')

小爱同学      小米同学      小孙同学      小杨同学  小牛奶   小猪
2019-10-03     1  0.733531 -0.539147  0.575574    1  1.0
2019-10-04     4  0.773296 -0.342647  0.951565    2  1.0

对缺失项赋值

In [141]:
df1.fillna(value =8848)

小爱同学      小米同学      小孙同学      小杨同学  小牛奶      小猪
2019-10-03     1  0.733531 -0.539147  0.575574    1     1.0
2019-10-04     4  0.773296 -0.342647  0.951565    2     1.0
2019-10-05     9 -1.661953  0.972271  0.159800    3  8848.0
2019-10-06    16 -0.177808  0.199810  0.735441    4  8848.0

对缺失项布尔赋值

In [143]:
-pd.isnull(df1)

小爱同学  小米同学  小孙同学  小杨同学   小牛奶     小猪
2019-10-03  True  True  True  True  True   True
2019-10-04  True  True  True  True  True   True
2019-10-05  True  True  True  True  True  False
2019-10-06  True  True  True  True  True  False

相关操作（跳过）

In [145]:
df.mean()

小爱同学    15.166667
小米同学     0.077417
小孙同学     0.307985
小杨同学     0.379147
小牛奶      3.500000
dtype: float64

In [146]:
df.mean(1)

2019-10-03    0.553992
2019-10-04    1.476443
2019-10-05    2.294024
2019-10-06    4.151488
2019-10-07    6.528684
2019-10-08    8.312828
Freq: D, dtype: float64

In [149]:
s = pd.Series([1,3,5,np.nan,6,8], index=dates).shift(1)
s


2019-10-03    NaN
2019-10-04    1.0
2019-10-05    3.0
2019-10-06    5.0
2019-10-07    NaN
2019-10-08    6.0
Freq: D, dtype: float64

In [150]:
df.sub(s,axis = 'index')

小爱同学      小米同学      小孙同学      小杨同学  小牛奶
2019-10-03   NaN       NaN       NaN       NaN  NaN
2019-10-04   3.0 -0.226704 -1.342647 -0.048435  1.0
2019-10-05   6.0 -4.661953 -2.027729 -2.840200  0.0
2019-10-06  11.0 -5.177808 -4.800190 -4.264559 -1.0
2019-10-07   NaN       NaN       NaN       NaN  NaN
2019-10-08  30.0 -6.399264 -5.356069 -6.680529  0.0

In [151]:
df.apply(np.cumsum)

小爱同学      小米同学      小孙同学      小杨同学  小牛奶
2019-10-03     1  0.733531 -0.539147  0.575574    1
2019-10-04     5  1.506827 -0.881794  1.527139    3
2019-10-05    14 -0.155126  0.090478  1.686939    6
2019-10-06    30 -0.332934  0.290287  2.422380   10
2019-10-07    55  0.863766  1.203978  2.955409   15
2019-10-08    91  0.464502  1.847909  2.274880   21

直方图和离散化

In [153]:
s= pd.Series(np.random.randint(0,7,size =10))
s


0    0
1    2
2    2
3    0
4    1
5    4
6    5
7    1
8    0
9    3
dtype: int64

In [154]:
s.value_counts()

0    3
2    2
1    2
5    1
4    1
3    1
dtype: int64

字符串方法 全变小写

In [155]:
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

合并

In [162]:

df = pd.DataFrame(np.random.randint(0,7,(10,10)))
df

0  1  2  3  4  5  6  7  8  9
0  4  4  5  3  6  0  3  4  0  6
1  4  4  6  2  4  2  3  6  2  6
2  2  2  6  6  3  3  0  5  3  4
3  4  4  0  4  2  2  0  0  0  5
4  0  5  0  2  3  3  4  6  6  5
5  0  0  4  1  3  6  2  5  5  0
6  2  1  6  5  1  5  2  0  5  3
7  3  1  2  3  5  2  0  5  5  0
8  6  0  4  4  0  3  2  6  5  4
9  3  0  5  1  1  5  2  5  5  5

In [170]:
 pieces = [df[:3], df[3:7]]
pieces

[   0  1  2  3  4  5  6  7  8  9
 0  4  4  5  3  6  0  3  4  0  6
 1  4  4  6  2  4  2  3  6  2  6
 2  2  2  6  6  3  3  0  5  3  4,    0  1  2  3  4  5  6  7  8  9
 3  4  4  0  4  2  2  0  0  0  5
 4  0  5  0  2  3  3  4  6  6  5
 5  0  0  4  1  3  6  2  5  5  0
 6  2  1  6  5  1  5  2  0  5  3]

In [169]:
pd.concat(pieces)

0  1  2  3  4  5  6  7  8  9
0  4  4  5  3  6  0  3  4  0  6
1  4  4  6  2  4  2  3  6  2  6
2  2  2  6  6  3  3  0  5  3  4
3  4  4  0  4  2  2  0  0  0  5
4  0  5  0  2  3  3  4  6  6  5
5  0  0  4  1  3  6  2  5  5  0
6  2  1  6  5  1  5  2  0  5  3
7  3  1  2  3  5  2  0  5  5  0
8  6  0  4  4  0  3  2  6  5  4
9  3  0  5  1  1  5  2  5  5  5

join操作

In [197]:
left = pd.DataFrame({'品牌': ['小米', '苹果'], '数量': [1, 2]})
right = pd.DataFrame({'品牌': ['小米', '苹果'], '库存': [4, 5]})
left

品牌  数量
0  小米   1
1  苹果   2

In [198]:
right

品牌  库存
0  小米   4
1  苹果   5

In [199]:
pd.merge(left,right,on ='品牌')

品牌  数量  库存
0  小米   1   4
1  苹果   2   5

In [202]:
 df = pd.DataFrame(np.random.randn(8, 4), columns=['A','B','C','D'])
df

A         B         C         D
0 -0.556911  0.513247 -1.161760 -0.140053
1 -1.010219 -0.741110 -1.362442  1.748832
2  0.666514  1.671654 -0.141651 -1.081204
3 -0.374127 -0.123594 -1.205136 -0.278136
4  0.617546 -0.665821 -0.050814 -0.606118
5  0.327432  0.800046 -0.055583 -1.519910
6  0.048836  2.863249 -0.059614 -1.359210
7  0.891507 -1.995725  2.813932  0.164731

In [206]:
s = df.iloc[3]
df.append(s, ignore_index=True)

A         B         C         D
0 -0.556911  0.513247 -1.161760 -0.140053
1 -1.010219 -0.741110 -1.362442  1.748832
2  0.666514  1.671654 -0.141651 -1.081204
3 -0.374127 -0.123594 -1.205136 -0.278136
4  0.617546 -0.665821 -0.050814 -0.606118
5  0.327432  0.800046 -0.055583 -1.519910
6  0.048836  2.863249 -0.059614 -1.359210
7  0.891507 -1.995725  2.813932  0.164731
8 -0.374127 -0.123594 -1.205136 -0.278136

In [211]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar','foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three','two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})
df


A      B         C         D
0  foo    one -1.708198  1.897539
1  bar    one -1.508160 -1.105506
2  foo    two -0.395177  0.600843
3  bar  three  0.206129 -0.042201
4  foo    two -0.608806 -0.623022
5  bar    two  1.064717 -0.322045
6  foo    one -0.792286  0.579669
7  foo  three  0.787300  1.276340

In [212]:
df.groupby('A').sum()

C         D
A                      
bar -0.237314 -1.469752
foo -2.717167  3.731369

In [217]:
df.groupby(['A','B']).sum()

C         D
A   B                        
bar one   -1.508160 -1.105506
    three  0.206129 -0.042201
    two    1.064717 -0.322045
foo one   -2.500484  2.477207
    three  0.787300  1.276340
    two   -1.003983 -0.022178

In [219]:
tuples = list(zip(*[['bar', 'bar', 'baz', 'baz','foo', 'foo', 'qux', 'qux'],['one', 'two', 'one', 'two','one', 'two', 'one', 'two']]))
tuples

[('bar', 'one'),
 ('bar', 'two'),
 ('baz', 'one'),
 ('baz', 'two'),
 ('foo', 'one'),
 ('foo', 'two'),
 ('qux', 'one'),
 ('qux', 'two')]

In [220]:
index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])
index

MultiIndex(levels=[['bar', 'baz', 'foo', 'qux'], ['one', 'two']],
           labels=[[0, 0, 1, 1, 2, 2, 3, 3], [0, 1, 0, 1, 0, 1, 0, 1]],
           names=['first', 'second'])

In [221]:
df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=['A', 'B'])
df

A         B
first second                    
bar   one    -1.386079  0.039940
      two     0.257594  0.866367
baz   one    -0.378905 -2.425962
      two     1.110257 -0.258173
foo   one    -0.070159 -0.042626
      two    -0.988782 -1.695079
qux   one     0.537163  1.692124
      two     0.932604 -0.043770